"""Update tables2

Revision ID: c0223b8555eb
Revises: 5bdeae9b162c
Create Date: 2023-12-08 15:31:20.859186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0223b8555eb'
down_revision: Union[str, None] = '5bdeae9b162c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
